### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [brianhempel/fuzzy_tools#4]
Dear Brian,

I've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. 

Thank you for the project!

**Comment by brianhempel** [comment]
:+1:

**Comment by brianhempel** [comment]
Though I admit I'm taking an NLP class right now and am using Python... :open_mouth:

**Comment by arbox** [comment]
Everybody uses Python but you can reuse your Python libraries in Ruby if your want.

**Comment by brianhempel** [comment]
Yeah—at the moment I just need bindings to NN frameworks. Didn't want the additional complication of having to fight with third party bindings if there were any problems.

**Comment by brianhempel** [comment]
Note I am on your list twice: the previous listing was under "Semantic Analysis". Not that I'm complaining.

**Comment by arbox** [comment]
Hi Brian,
the list is work in progress, feel free to send me pull request if you think something is strange!
